import { expect, test } from '@playwright/test'
import { installKomariFixture } from '../visual/fixtures/komari'

test('partial return-route results stay in their carrier columns', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 })
  await installKomariFixture(page, { opsDashboard: true, returnRouteTag: 'partial' })
  await page.goto('/')
  const card = page.locator('[data-transit-node-card-size]').filter({ has: page.locator('[data-node-route-panel]') }).first()
  const rows = card.locator('[data-node-route-panel] [data-carrier]')
  await expect(rows).toHaveCount(2)
  await expect(card.locator('[data-node-route-panel] [data-carrier="CU"]')).toHaveCount(0)
  for (const [carrier, column] of [['CT', 1], ['CM', 2]] as const) {
    const route = await card.locator(`[data-node-route-panel] [data-carrier="${carrier}"]`).boundingBox()
    const quality = await card.locator('[data-node-carrier-row]').nth(column).boundingBox()
    expect(route).not.toBeNull()
    expect(quality).not.toBeNull()
    expect(Math.abs(route!.x - quality!.x)).toBeLessThanOrEqual(1)
    expect(Math.abs(route!.width - quality!.width)).toBeLessThanOrEqual(1)
  }
})

test('guest topology navigation has a read-only empty destination', async ({ page }) => {
  await installKomariFixture(page, { opsDashboard: true, emptyTopology: true })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '还没有配置线路' })).toBeVisible()
  await page.getByRole('navigation', { name: '监控视图' }).getByRole('button', { name: '拓扑', exact: true }).click()
  await expect(page.getByRole('heading', { name: '还没有配置线路' })).toBeInViewport()
  await expect(page.getByRole('button', { name: '配置第一条线路' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '管理', exact: true })).toHaveCount(0)
})

for (const pageAnimation of [false, true]) {
  test(`redesign navigation preserves detail return with animations ${pageAnimation ? 'enabled' : 'disabled'}`, async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    page.on('console', (message) => {
      if (message.text().includes('non-element root'))
        errors.push(message.text())
    })
    await page.setViewportSize({ width: 1280, height: 900 })
    await installKomariFixture(page, { opsDashboard: true, pageAnimation, returnRouteTag: 'fresh' })
    await page.goto('/')
    const navigation = page.getByRole('navigation', { name: '监控视图' })
    await expect(page.getByRole('heading', { name: '网络总览' })).toBeVisible()
    await navigation.getByRole('button', { name: '拓扑', exact: true }).click()
    await expect(page.getByRole('heading', { name: '线路拓扑' })).toBeInViewport()
    await expect(navigation.getByRole('button', { name: '拓扑', exact: true })).toHaveAttribute('aria-current', 'location')
    await expect(page.locator('[data-topology-route-score]').first()).toContainText('查看详情')
    await page.locator('[data-topology-route-score]').first().click()
    const detail = page.getByRole('dialog')
    await expect(detail).toContainText('近 1 小时线路健康评分')
    await detail.getByRole('button', { name: '查看异常时间线' }).click()
    const timeline = page.getByRole('dialog', { name: '异常时间线' })
    await expect(timeline).toBeVisible()
    await timeline.getByRole('button', { name: '关闭', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(1)
    await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
    await navigation.getByRole('button', { name: '总览', exact: true }).click()
    await expect(page.getByRole('heading', { name: '网络总览' })).toBeInViewport()
    await expect(navigation.getByRole('button', { name: '总览', exact: true })).toHaveAttribute('aria-current', 'location')
    await page.getByRole('button', { name: '打开 主控-洛杉矶 的详细信息' }).click()
    await expect(page.getByText('硬件信息')).toBeVisible()
    await page.getByRole('button', { name: '返回上一页' }).click()
    await expect(page.getByRole('heading', { name: '网络总览' })).toBeVisible()
    await expect(page.locator('[data-carrier-columns]').first()).toBeVisible()
    expect(errors).toEqual([])
  })
}

test('mobile WebKit redesign fits narrow cards and keeps navigation labels visible', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 800 })
  await installKomariFixture(page, { opsDashboard: true, authenticated: true, nodeCardWorstCase: true, returnRouteTag: 'fresh' })
  await page.goto('/')
  const navigation = page.getByRole('navigation', { name: '监控视图' })
  await expect(navigation.getByRole('button', { name: '拓扑', exact: true })).toBeVisible()
  await expect(page.locator('[data-carrier-columns]').first()).toBeVisible()
  expect(await page.locator('[data-carrier-columns]').first().evaluate(element => getComputedStyle(element).gridTemplateColumns.split(' ').length)).toBe(3)
  await navigation.getByRole('button', { name: '拓扑', exact: true }).click()
  await expect(page.getByRole('heading', { name: '线路拓扑' })).toBeInViewport()
  await expect(page.locator('[data-topology-mobile-route]')).toHaveCount(2)
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBe(0)
  const header = await page.locator('.site-header').boundingBox()
  const heading = await page.getByRole('heading', { name: '线路拓扑' }).boundingBox()
  expect(heading!.y).toBeGreaterThanOrEqual(header!.y + header!.height)
})
