import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import process from 'node:process'

const root = process.cwd()
const sourceDir = join(root, 'src')
const outputFile = join(root, 'src/utils/iconify.icons.ts')
const ICON_PATTERN = /(?:icon-park-outline|tabler|carbon|simple-icons|lucide):[a-z0-9-]+/gi
const SOURCE_FILE_PATTERN = /\.(?:ts|vue)$/
const checkOnly = process.argv.includes('--check')

function walk(dir: string, files: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    const stat = statSync(full)
    if (stat.isDirectory()) {
      walk(full, files)
      continue
    }
    if (SOURCE_FILE_PATTERN.test(entry) && !entry.endsWith('iconify.icons.ts'))
      files.push(full)
  }
  return files
}

const found = new Set<string>()
for (const file of walk(sourceDir)) {
  const matches = readFileSync(file, 'utf8').match(ICON_PATTERN) ?? []
  for (const match of matches)
    found.add(match.toLowerCase())
}

if (found.size === 0)
  throw new Error('No Iconify icon names found in src/.')

const byPrefix = new Map<string, Set<string>>()
for (const icon of found) {
  const [prefix, name] = icon.split(':')
  if (!prefix || !name)
    continue
  const names = byPrefix.get(prefix) ?? new Set<string>()
  names.add(name)
  byPrefix.set(prefix, names)
}

const collections: string[] = []
const missing: string[] = []

for (const [prefix, names] of [...byPrefix.entries()].sort(([left], [right]) => left.localeCompare(right))) {
  const collectionPath = join(root, 'node_modules/@iconify/json/json', `${prefix}.json`)
  if (!existsSync(collectionPath))
    throw new Error(`Missing Iconify collection JSON: ${prefix}`)

  const collection = JSON.parse(readFileSync(collectionPath, 'utf8')) as {
    prefix: string
    icons: Record<string, { body: string, width?: number, height?: number }>
    width?: number
    height?: number
  }

  const icons: Record<string, { body: string, width?: number, height?: number }> = {}
  for (const name of [...names].sort()) {
    const icon = collection.icons[name]
    if (!icon) {
      missing.push(`${prefix}:${name}`)
      continue
    }
    icons[name] = icon
  }

  collections.push(JSON.stringify({
    prefix: collection.prefix,
    width: collection.width,
    height: collection.height,
    icons,
  }))
}

if (missing.length)
  throw new Error(`Unknown Iconify icons: ${missing.join(', ')}`)

const generated = `// Generated by scripts/generate-icon-collection.ts. Do not edit by hand.
import { addCollection } from '@iconify/vue/offline'

const collections = ${JSON.stringify(collections.map(item => JSON.parse(item)), null, 2)} as const

export const bundledIconNames = ${JSON.stringify([...found].sort(), null, 2)} as const

export function registerBundledIcons(): void {
  for (const collection of collections)
    addCollection(collection)
}
`

if (checkOnly) {
  if (!existsSync(outputFile) || readFileSync(outputFile, 'utf8') !== generated) {
    console.error(`Icon collection is stale. Run bun scripts/generate-icon-collection.ts`)
    process.exit(1)
  }
  console.log(`Icon collection is current (${found.size} icons).`)
  process.exit(0)
}

writeFileSync(outputFile, generated)
console.log(`Wrote ${relative(root, outputFile)} with ${found.size} icons.`)
